package view;

/**
 *
 * @author Alexandre / Elias / Elzio
 */
public class Eireli extends javax.swing.JFrame {

    /**
     * Creates new form Eireli
     */
    public Eireli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuCadCli = new javax.swing.JMenuItem();
        jMenuConsCli = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenu();
        jMenuCadPro = new javax.swing.JMenuItem();
        jMenuConsProd = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/application_add.png"))); // NOI18N
        jMenuCadastro.setText("Cadastros");

        jMenuCliente.setText("Cliente");

        jMenuCadCli.setText("Cadastro");
        jMenuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCliActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuCadCli);

        jMenuConsCli.setText("Consulta");
        jMenuConsCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsCliActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuConsCli);

        jMenuCadastro.add(jMenuCliente);

        jMenuProduto.setText("Produto");

        jMenuCadPro.setText("Cadastro");
        jMenuCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadProActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuCadPro);

        jMenuConsProd.setText("Consulta");
        jMenuConsProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsProdActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuConsProd);

        jMenuCadastro.add(jMenuProduto);

        jMenuBar.add(jMenuCadastro);

        jMenuOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/application_lightning.png"))); // NOI18N
        jMenuOperacao.setText("Operações");

        jMenuVenda.setText("Venda");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItem1);

        jMenuOperacao.add(jMenuVenda);

        jMenuBar.add(jMenuOperacao);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCliActionPerformed
        new Cad_Cli().setVisible(true);
    }//GEN-LAST:event_jMenuCadCliActionPerformed

    private void jMenuConsCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsCliActionPerformed
        new ConsultaCliente().setVisible(true);
    }//GEN-LAST:event_jMenuConsCliActionPerformed

    private void jMenuCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadProActionPerformed
        new Cad_Prod().setVisible(true);
    }//GEN-LAST:event_jMenuCadProActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Cad_Venda().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuConsProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsProdActionPerformed
        new ConsultaProduto().setVisible(true);
    }//GEN-LAST:event_jMenuConsProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eireli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eireli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eireli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eireli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eireli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuCadCli;
    private javax.swing.JMenuItem jMenuCadPro;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuConsCli;
    private javax.swing.JMenuItem jMenuConsProd;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
